### ISSUE TITLE
Copy/Paste Between Maps

### ISSUE THREAD

**Issue by JustTheJamieJoyce** [debate-map/app#13]
See visualization [here](https://www.canva.com/design/DAEWVTFcUsc/gZiQWuIcqO2ZQSjrBVADIA/view?utm_content=DAEWVTFcUsc&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)

Currently, the copy/paste node feature is only possible within a single map, we need copy/paste capabilities between maps, or to be able to copy separate maps into other maps. Said another way, we need to be able to create various individual maps and be able copy/paste them together to unify them in a larger, separate map. We need to preserve the ability for maps to auto-update all copies once altered.

In addition to copy/paste functionality between maps, we need the ability to "turn off and on" the visibility of different parts of the tree in the individual maps, when copied to the larger map, for the purpose of maintaining relevance. 

For example - a user has been working on an individual map (A) that includes all claims related to extreme weather events. When another user is copying over that map (A) to be included as a part of a different map (B), they've discovered that map (A) needs to be broken up - or - they will need to make two distinct copies of map (A) in two distinct places in map (B), because map (B) has distinct trees for discussing the (1) severity of extreme weather events and the (2) occurrence of extreme weather events. Map (A) contains all the claims related to (1) severity and (2) occurrence together, but if copied into both places in map (B), they bring extraneous, unrelated claims in each place. Therefore, one copy of map (A) to map (B) needs to be able to "hide" or "turn off" claims about (1), while the second copy of map (A) to a different location in map (B) needs to be able to "hide" or "turn off" claims about (2).

**Comment by Venryx** [comment]
Sounds good.

The more complicated portion is definitely the second part, regarding the toggling on and off of specific subtrees, depending on which map is currently open.

That said, I've already come up with an approach for edits/permissions that should be able to solve both problems. It's a pretty big refactor, but it should achieve those two goals, as well as provide flexibility for the future.

One complication point is that the changes will mean we also need to update the GAD frontend demo app to match the new data structure. So I'll need to coordinate with Mike when I'm about to activate the changes, to keep the GAD frontend app working. (He'll need to update the `@debate-map/server-link` package, as well as make a few changes to how the nodes are retrieved; but I can talk with him about this and/or add the code changes myself later.)
