### ISSUE TITLE
Optimize the sql `search_for_external_ids` function

### ISSUE THREAD

**Issue by Venryx** [debate-map/app#223]

**Comment by maparent** [comment]
Also add a "ClaimMiner quote" source type, please!

**Comment by Venryx** [comment]
Sounds good, but do ClaimMiner quotes have a UUID that can be inserted there? (I noticed one of the ClaimMiner tasks said "Switch to UUIDs")

**Comment by maparent** [comment]
No, I'm currently using numeric IDs, but it's an external ID, not the DebateMap Id. is the hypothesis external ID a UUID?

**Comment by Venryx** [comment]
Ah good question; now that I think about it, the hypothesis annotation ID did not look like a UUID (though can't remember for sure).

Anyway, I guess it doesn't matter, so long as the ids are "stable" in both Hypothesis and ClaimMiner.

**Comment by Venryx** [comment]
Completed. (though we'll want to optimize the sql function more; atm it takes ~400ms to complete [!], despite the attempted index creation)

**Comment by Venryx** [comment]
Actually, I'll leave this issue open until the function is optimized some more.
