### ISSUE TITLE
Maybe make-so the Tiltfile automatically retrieves the ip-address of the k8s node, for use as load-balancer external-ip

### ISSUE THREAD

**Issue by Venryx** [debate-map/app#268]

**Comment by maparent** [comment]
From the command line, we can get all the nodes with `kubectl get node -A`, and then use the node pool's name as an argument in in 
`kubectl get node <node-pool-name> -o=json | jq '.status.addresses[] | if .type == "InternalIP" then .address else empty end '`
So let's see if we can do the same within tilt.

**Comment by Venryx** [comment]
Tilt-files can run local commands using the `local` function: https://docs.tilt.dev/api.html#api.local

As for extracting the specific address field desired, a cross-platform alternative to `jq` could be the `-o jsonpath` k8s flag: https://kubernetes.io/docs/reference/kubectl/jsonpath/

**Comment by Venryx** [comment]
And for inserting that address into the `node_port_service.yaml` file, you can use the custom `ReadFileWithReplacements` function. Example here: https://github.com/debate-map/app/blob/ae0a3fb9410dea16f816ac62fe204e4367b3d901/Tilt/App.star#L85
