### ISSUE TITLE
Error dump from left had console as soon as I signed in with google

### ISSUE THREAD

**Issue by ran88dom99** [debate-map/app#8]
An error has occurred: Permission denied to access property "$mirror" on cross-origin object
GetMirrorOfMobXTree@https://debatemap.app/app.js?54d7db6b97962faf6c28:302611:9
StartUpdatingMirrorOfMobXTree/<@https://debatemap.app/app.js?54d7db6b97962faf6c28:302634:73
reactionRunner@https://debatemap.app/app.js?54d7db6b97962faf6c28:219690:13
trackDerivedFunction@https://debatemap.app/app.js?54d7db6b97962faf6c28:218368:24
./node_modules/mobx/lib/mobx.module.js/</Reaction.prototype.track@https://debatemap.app/app.js?54d7db6b97962faf6c28:219394:42
autorun/reaction<@https://debatemap.app/app.js?54d7db6b97962faf6c28:219671:18
./node_modules/mobx/lib/mobx.module.js/</Reaction.prototype.runReaction@https://debatemap.app/app.js?54d7db6b97962faf6c28:219360:26
runReactionsHelper@https://debatemap.app/app.js?54d7db6b97962faf6c28:219497:35
reactionScheduler@https://debatemap.app/app.js?54d7db6b97962faf6c28:219475:47
reactionScheduler/<@https://debatemap.app/app.js?54d7db6b97962faf6c28:219504:71
ej@https://debatemap.app/app.js?54d7db6b97962faf6c28:259194:323
reactionScheduler@https://debatemap.app/app.js?54d7db6b97962faf6c28:219504:47
runReactions@https://debatemap.app/app.js?54d7db6b97962faf6c28:219480:22
endBatch@https://debatemap.app/app.js?54d7db6b97962faf6c28:219180:9
_endAction@https://debatemap.app/app.js?54d7db6b97962faf6c28:218566:5
executeAction@https://debatemap.app/app.js?54d7db6b97962faf6c28:218520:19
runInAction@https://debatemap.app/app.js?54d7db6b97962faf6c28:219647:12
InitSubs/<@https://debatemap.app/app.js?54d7db6b97962faf6c28:212215:69
./node_modules/@firebase/util/dist/index.cjs.js/</ObserverProxy.prototype.next/<@https://debatemap.app/app.js?54d7db6b97962faf6c28:113166:22
./node_modules/@firebase/util/dist/index.cjs.js/</ObserverProxy.prototype.sendOne/<@https://debatemap.app/app.js?54d7db6b97962faf6c28:113276:23

**Comment by ran88dom99** [comment]
Win 8 and firefox 80.

**Comment by Venryx** [comment]
Thank you for the report, I will look into it.

What action causes the error to show up? Simply loading the page? Signing in? Trying to add or remove a node?

**Comment by Venryx** [comment]
Nevermind, I figured out how to replicate the error (had to sign out then sign back in), and fixed it. (no errors seen anymore in either Chrome or Firefox)

Let me know if the error persists for you, of course.
